# Generated by Django 4.0.2 on 2022-02-20 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entertainment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('related_comments', models.ManyToManyField(to='entertainment.Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('sport', 'Sport'), ('tech', 'Tech'), ('shop', 'Shop'), ('study', 'Study')], default='cafe', max_length=20),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainment.comment')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='entertainment.place')),
                ('user', models.OneToOneField(on_delete=models.SET(entertainment.models.get_sentinel_user), related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
