# Generated by Django 4.0.2 on 2022-02-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_comment_alter_place_type_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_comments',
            field=models.ManyToManyField(blank=True, to='entertainment.Comment'),
        ),
    ]
