# Generated by Django 4.0.2 on 2022-02-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_alter_comment_related_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainment.comment'),
        ),
    ]
