# Generated by Django 4.0.2 on 2022-02-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_alter_rate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='entertainment.place'),
        ),
    ]
