# Generated by Django 4.0.2 on 2022-02-26 15:39

from django.conf import settings
from django.db import migrations, models
import entertainment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment', '0005_alter_rate_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(entertainment.models.get_sentinel_user), related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
