# Generated by Django 4.0.2 on 2022-02-26 15:47

from django.db import migrations, models
import entertainment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[entertainment.validators.validate_rating]),
        ),
    ]
