# Generated by Django 4.0.2 on 2022-02-26 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment', '0007_alter_rate_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('place', 'user')},
        ),
    ]
