# Generated by Django 4.0.2 on 2022-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
