# Generated by Django 4.0.2 on 2022-02-26 19:25

from django.conf import settings
from django.db import migrations, models
import entertainment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment', '0009_alter_comment_created_at_alter_rate_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(entertainment.models.get_sentinel_user), related_name='users_comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
