# Generated by Django 4.0.2 on 2022-02-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0010_alter_comment_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
