# Generated by Django 4.0.2 on 2022-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(default='shop', max_length=200),
        ),
    ]
